name: climatematch
channels:
 - conda-forge
 - nodefaults
dependencies:
 - climlab
 - ecco_v4_py
 - esmf
 - nltk
 - openpyxl
 - pip
 - pooch
 - pygeos
 - pythia-datasets
 - pyworld3 # needed for W2D3
 - texttable
 - wordcloud
 - pip:
   - afinn
   - pyleoclim
   - "mystatsfunctions @ https://github.com/njleach/mystatsfunctions/archive/main.zip"
   - https://github.com/mptouzel/PyDICE/archive/master.zip # for W2D3 Tutorial 2

